### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Luk164** [wegylexy/SaitekDirectOutput#1]
Hello, I am having some trouble building this wrapper, would you mind to assist me? I know this is an old project but I did not find any recent alternatives. Thank you

**Comment by wegylexy** [comment]
What does Visual Studio say about your issue?

**Comment by Luk164** [comment]
It cannot link to external dependencies, though VS does see them. I have managed to find this one though and it works fine for me https://github.com/nikburnt/saitek-direct-output-csharp-wrapper. I have already started extending it to create a high-level API to make it easy to work with.

**Comment by wegylexy** [comment]
Confirm 32-bit vs 64-bit? What external dependencies? Can you paste the exact error messages here?

**Comment by Luk164** [comment]
I tried to build it again today to get to the errors and everything worked fine. Must have been some bug on my end. Anyway, this is also a pretty good implementation of directOutput, now I am torn on which one to use...
